DROP TABLE IF EXISTS cr.mobileapp;
CREATE EXTERNAL TABLE IF NOT EXISTS cr.mobileapp
(
EMAIL_ADDRESS VARCHAR(100),
REGION VARCHAR(2),
FNAME VARCHAR(100),
LNAME VARCHAR(100),
CAPTURE_DATE VARCHAR(17),
MODIFIED_DATE VARCHAR(17),
BATCH_ID VARCHAR(20),
DATE_PROCESSED VARCHAR(50)
)
COMMENT 'mobileapp data in cr'
PARTITIONED BY (par_date VARCHAR(50))
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION '/data/cr/mobileapp';
