DROP TABLE IF EXISTS raw.mobileapp;
CREATE EXTERNAL TABLE IF NOT EXISTS raw.mobileapp
(
EMAIL_ADDRESS VARCHAR(100),
REGION VARCHAR(2),
FNAME VARCHAR(100),
LNAME VARCHAR(100),
CAPTURE_DATE VARCHAR(17),
MODIFIED_DATE VARCHAR(17)
)
COMMENT 'mobileapp data in raw'
PARTITIONED BY (par_date VARCHAR(50))
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
tblproperties("skip.header.line.count"="1");
