DROP TABLE IF EXISTS stage.mobileapp;
CREATE EXTERNAL TABLE IF NOT EXISTS stage.mobileapp
(
EMAIL_ADDRESS VARCHAR(100),
REGION VARCHAR(2),
FNAME VARCHAR(100),
LNAME VARCHAR(100),
CAPTURE_DATE VARCHAR(17),
MODIFIED_DATE VARCHAR(17),
BATCH_ID VARCHAR(20),
DATE_PROCESSED VARCHAR(50)
)
COMMENT 'mobileapp data in stage'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
LOCATION '/data/stage/mobileapp';
